name: 💡 Feature Request
description: Sugerir uma nova funcionalidade ou melhoria
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma melhoria! Suas ideias ajudam a tornar o projeto melhor para toda a comunidade.

  - type: textarea
    id: problem
    attributes:
      label: 🤔 Problema ou Necessidade
      description: Que problema esta funcionalidade resolveria?
      placeholder: Ex. É difícil filtrar dados por nível hierárquico...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Solução Proposta
      description: Descreva sua ideia de solução
      placeholder: Ex. Adicionar uma função de filtro que...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 📂 Categoria
      description: Que tipo de melhoria você está sugerindo?
      options:
        - "📊 Processamento de dados"
        - "🔧 Scripts e ferramentas"
        - "📚 Documentação"
        - "🎨 Interface/UX"
        - "📱 Nova funcionalidade"
        - "⚡ Performance"
        - "🛡️ Segurança"
        - "🧪 Testes"
        - "📦 Distribuição/Deploy"
        - "🔗 Integração"
        - "📈 Analytics"
        - "🎯 Outro"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 📈 Prioridade
      description: Qual a importância desta funcionalidade?
      options:
        - "🔥 Alta - Funcionalidade essencial"
        - "📊 Média - Melhoria importante"
        - "💡 Baixa - Nice to have"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternativas Consideradas
      description: Você considerou outras soluções?
      placeholder: Ex. Tentei usar X, mas não funcionou porque...

  - type: textarea
    id: examples
    attributes:
      label: 📝 Exemplos de Uso
      description: Como esta funcionalidade seria usada?
      placeholder: |
        ```python
        # Exemplo de como a nova funcionalidade seria usada
        df_filtered = filter_by_hierarchy(df, level=2, subject="Direito")
        ```

  - type: textarea
    id: implementation
    attributes:
      label: 🛠️ Sugestão de Implementação
      description: Tem alguma ideia de como implementar? (opcional)
      placeholder: Ex. Poderia adicionar um parâmetro no script clean_data.py...

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribuição
      description: Você gostaria de ajudar a implementar?
      options:
        - label: Posso ajudar a implementar esta funcionalidade
          required: false
        - label: Posso ajudar com testes
          required: false
        - label: Posso ajudar com documentação
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: ✔️ Checklist
      description: Confirme que você verificou os itens abaixo
      options:
        - label: Verifiquei se não há requests similares já abertos
          required: true
        - label: Esta funcionalidade beneficiaria outros usuários
          required: true
        - label: Li a documentação e guia de contribuição
          required: false